### ISSUE TITLE
Fan placement

### ISSUE THREAD

**Issue by Johboh** [e-tinkers/TinyReflowControllerV3#1]
Hi!
Not an issue, but I can see in the source code that you have added a fan :).
Where did you place/mount this? A photo would be helpful!

I just bought a 946-1010 and plan on replacing my existing [reflow plate](https://github.com/Johboh/Solder-Reflow-Plate) (with this one that can reach higher temperatures).

//Johan

**Comment by e-tinkers** [comment]
I eventually didn't install the fan. I simply took the PCB off the hotplate when the reflow is done instead of activating the fan and wait for the hot plate to cool down as it took too long.

**Comment by Johboh** [comment]
OK!
I will try with a big fan and see how it works out. Otherwise maybe overengineer a solution like this: https://www.youtube.com/watch?v=dwdYV_DlkiY

**Comment by Johboh** [comment]
I did some overengineering :) 


![PXL_20231126_131705865](https://github.com/e-tinkers/TinyReflowControllerV3/assets/4701462/080bdad0-3e6b-428f-855a-a3c5f546665c)

https://github.com/e-tinkers/TinyReflowControllerV3/assets/4701462/7d90f3a2-14cb-41f3-9a85-0a1eb720449e
